Added file modifier script
Script adds an editurl to all twin YAML docs

diff --git a/.github/workflows/file-modifier.yml b/.github/workflows/file-modifier.yml
--- a/.github/workflows/file-modifier.yml
+++ b/.github/workflows/file-modifier.yml
@@ -25,6 +25,11 @@ jobs:
       run: |
         git config --local user.email "57953088+juusoautiosalo@users.noreply.github.com"
         git config --local user.name "actions-push-test[bot]"
+    - name: Modify YAMLs
+      run: |
+        chmod +x "${GITHUB_WORKSPACE}/.github/script-modify-yamls.sh"
+        "${GITHUB_WORKSPACE}/.github/script-modify-yamls.sh"
+        git commit -m "Automodified YAML file" -a || echo "Warning: git commit returned error code $? (Hopefully nothing to commit)"
     - name: Generate JSONs from YAMLs
       run: |
         chmod +x "${GITHUB_WORKSPACE}/.github/script-yamls-to-jsons.sh"
